"""Additional employer sources researched for the three career tracks.

The list intentionally assigns every employer to one primary track.  This keeps
the active-track scan bounded while adding 100 distinct employers overall.
Direct ATS boards use their native collector; official pages use the bounded
official collector and may legitimately return no current Israel vacancies.
"""

from __future__ import annotations


def _source(
    identifier: str,
    company: str,
    track: str,
    logo_domain: str,
    *,
    url: str = "",
    kind: str = "official_careers",
    enabled: bool | None = None,
) -> dict[str, object]:
    return {
        "name": f"{company} Careers Israel",
        "kind": kind,
        "identifier": identifier,
        "company_name": company,
        "track": track,
        "logo_domain": logo_domain,
        "url": url,
        # Generic careers pages stay visible in the researched catalog but do
        # not consume scheduled scan time until a structured board is verified.
        "enabled": kind != "official_careers" if enabled is None else enabled,
        "validation_status": "verified" if (kind != "official_careers" or enabled is True) else "pending_adapter",
    }


EXPANDED_EMPLOYER_SOURCES: tuple[dict[str, str], ...] = (
    _source("atbayjobs", "At-Bay", "cs", "at-bay.com", kind="greenhouse"),
    _source("doitintl", "DoiT", "cs", "doit.com", kind="greenhouse"),
    _source("walkme", "WalkMe", "cs", "walkme.com", kind="lever"),
    _source("lendbuzz", "Lendbuzz", "cs", "lendbuzz.com", kind="lever"),
    _source("tonkean", "Tonkean", "cs", "tonkean.com", kind="lever"),
    _source("logz", "Logz.io", "cs", "logz.io", kind="lever"),
    _source("Zadara", "Zadara", "cs", "zadara.com", kind="lever"),
    _source("palantir", "Palantir", "cs", "palantir.com", kind="lever"),
    _source("augury", "Augury", "cs", "augury.com", kind="greenhouse"),
    _source("transmitsecurity", "Transmit Security", "cs", "transmitsecurity.com", kind="greenhouse"),
    _source("axonius", "Axonius", "cs", "axonius.com", kind="greenhouse"),
    _source("controlup", "ControlUp", "cs", "controlup.com", kind="lever"),
    _source("okta", "Okta", "cs", "okta.com", kind="greenhouse"),
    _source("gitlab", "GitLab", "cs", "gitlab.com", kind="greenhouse"),
    _source("elastic", "Elastic", "cs", "elastic.co", kind="greenhouse"),
    _source("datadog", "Datadog", "cs", "datadoghq.com", kind="greenhouse"),
    _source("mongodb", "MongoDB", "cs", "mongodb.com", kind="greenhouse"),
    _source("stripe", "Stripe", "cs", "stripe.com", kind="greenhouse"),
    _source("rubrik", "Rubrik", "cs", "rubrik.com", kind="greenhouse"),
    _source("zscaler", "Zscaler", "cs", "zscaler.com", kind="greenhouse"),
    _source("jfrog", "JFrog", "cs", "jfrog.com", kind="greenhouse"),
    _source("snyk", "Snyk", "cs", "snyk.io", url="https://snyk.io/careers/all-jobs/"),
    _source("rapyd", "Rapyd", "cs", "rapyd.net", url="https://www.rapyd.net/company/careers-search/", enabled=True),
    _source("tipalti", "Tipalti", "cs", "tipalti.com", url="https://tipalti.com/company/careers/", enabled=True),
    _source("lightricks", "Lightricks", "cs", "lightricks.com", kind="greenhouse"),
    _source("guesty", "Guesty", "cs", "guesty.com", url="https://www.guesty.com/careers/", enabled=True),
    _source("papaya-global", "Papaya Global", "cs", "papayaglobal.com", url="https://www.papayaglobal.com/careers/", enabled=True),
    _source("hibob", "HiBob", "cs", "hibob.com", url="https://www.hibob.com/careers/", enabled=True),
    _source("yotpo", "Yotpo", "cs", "yotpo.com", kind="greenhouse"),
    _source("fundbox", "Fundbox", "cs", "fundbox.com", url="https://fundbox.com/careers/", enabled=True),
    _source("fireblocks", "Fireblocks", "cs", "fireblocks.com", kind="greenhouse"),
    _source("xm-cyber", "XM Cyber", "cs", "xmcyber.com", url="https://xmcyber.com/careers/"),
    _source("pentera", "Pentera", "cs", "pentera.io", url="https://pentera.io/careers/", enabled=True),
    _source("island", "Island", "cs", "island.io", url="https://www.island.io/careers", enabled=True),
    _source("cyera", "Cyera", "cs", "cyera.io", url="https://www.cyera.com/careers", enabled=True),
    _source("upwind", "Upwind", "cs", "upwind.io", url="https://www.upwind.io/careers", enabled=True),
    _source("grip-security", "Grip Security", "cs", "grip.security", url="https://www.grip.security/careers", enabled=True),
    _source("astrix-security", "Astrix Security", "cs", "astrix.security", url="https://astrix.security/careers/"),
    _source("reco", "Reco", "cs", "reco.ai", url="https://www.reco.ai/careers", enabled=True),
    _source("bigid", "BigID", "cs", "bigid.com", kind="greenhouse"),
    _source("starkware", "StarkWare", "cs", "starkware.co", url="https://starkware.co/careers/"),
    _source("saltsecurity", "Salt Security", "cs", "salt.security", kind="greenhouse"),
    _source("coralogix", "Coralogix", "cs", "coralogix.com", url="https://coralogix.com/careers/", enabled=True),
    _source("atera", "Atera", "cs", "atera.com", url="https://www.atera.com/careers/", enabled=True),
    _source("cloudinary", "Cloudinary", "cs", "cloudinary.com", kind="lever"),
    _source("kaltura", "Kaltura", "cs", "kaltura.com", url="https://corp.kaltura.com/company/careers/", enabled=True),
    _source("natural-intelligence", "Natural Intelligence", "cs", "naturalint.com", url="https://www.naturalint.com/careers/", enabled=True),
    _source("payoneer", "Payoneer", "cs", "payoneer.com", kind="greenhouse"),
    _source("etoro", "eToro", "cs", "etoro.com", url="https://www.etoro.com/about/careers/", enabled=True),
    _source("lemonade", "Lemonade", "cs", "lemonade.com", url="https://www.lemonade.com/careers", enabled=True),
    _source("earnix", "Earnix", "cs", "earnix.com", url="https://earnix.com/careers/", enabled=True),
    _source("nayax", "Nayax", "cs", "nayax.com", url="https://www.nayax.com/careers/", enabled=True),
    _source("global-e", "Global-e", "cs", "global-e.com", url="https://www.global-e.com/careers/", enabled=True),
    _source("priority-software", "Priority Software", "cs", "priority-software.com", url="https://www.priority-software.com/careers/"),
    _source("sapiens", "Sapiens", "cs", "sapiens.com", url="https://sapiens.com/careers/"),
    _source("amdocs", "Amdocs", "cs", "amdocs.com", url="https://jobs.amdocs.com/"),
    _source("verint", "Verint", "cs", "verint.com", url="https://www.verint.com/careers/"),
    _source("unity", "Unity", "cs", "unity.com", url="https://unity.com/careers/positions", enabled=True),
    _source("oracle", "Oracle", "cs", "oracle.com", url="https://careers.oracle.com/jobs/"),
    _source("sap-israel", "SAP", "cs", "sap.com", url="https://jobs.sap.com/go/SAP-Jobs-in-Israel/851401/"),
    _source("dell", "Dell Technologies", "ee", "dell.com", url="https://jobs.dell.com/"),
    _source("hp", "HP", "ee", "hp.com", url="https://jobs.hp.com/"),
    _source("WesternDigital", "Western Digital", "ee", "westerndigital.com", kind="smartrecruiters"),
    _source("analog-devices", "Analog Devices", "ee", "analog.com", url="https://careers.analog.com/"),
    _source("solaredge", "SolarEdge", "ee", "solaredge.com", url="https://careers.solaredge.com/", enabled=True),
    _source("stratasys", "Stratasys", "ee", "stratasys.com", url="https://careers.stratasys.com/"),
    _source("motorola-solutions", "Motorola Solutions", "ee", "motorolasolutions.com", url="https://www.motorolasolutions.com/en_us/about/careers.html", enabled=True),
    _source("ericsson", "Ericsson", "ee", "ericsson.com", url="https://www.ericsson.com/en/careers"),
    _source("nokia", "Nokia", "ee", "nokia.com", url="https://www.nokia.com/about-us/careers/"),
    _source("ge-healthcare", "GE HealthCare", "ee", "gehealthcare.com", url="https://careers.gehealthcare.com/global/en", enabled=True),
    _source("elspec", "Elspec", "ee", "elspec-ltd.com", url="https://www.elspec-ltd.com/careers/"),
    _source("jabil-israel", "Jabil", "ee", "jabil.com", url="https://careers.jabil.com/"),
    _source("boston-scientific", "Boston Scientific", "ee", "bostonscientific.com", url="https://www.bostonscientific.com/en-US/careers.html"),
    _source("orcam", "OrCam", "ee", "orcam.com", url="https://www.orcam.com/en-us/careers/"),
    _source("optimove", "Optimove", "cs", "optimove.com", kind="greenhouse"),
    _source("personetics", "Personetics", "cs", "personetics.com", url="https://personetics.com/careers/", enabled=True),
    _source("deep-instinct", "Deep Instinct", "cs", "deepinstinct.com", url="https://www.deepinstinct.com/careers"),
    _source("netafim", "Netafim", "iem", "netafim.com", url="https://careers.netafim.com/", enabled=True),
    _source("zim", "ZIM", "iem", "zim.com", url="https://www.zim.com/careers/job-opportunities"),
    _source("kornit-digital", "Kornit Digital", "iem", "kornit.com", url="https://careers.kornit.com/all-positions/", enabled=True),
    _source("ormat", "Ormat Technologies", "iem", "ormat.com", url="https://www.ormat.com/en/company/careers/"),
    _source("ide-technologies", "IDE Technologies", "iem", "ide-tech.com", url="https://ide-tech.com/en/career/"),
    _source("sodastream", "SodaStream", "iem", "sodastream.com", url="https://sodastream.com/pages/careers"),
    _source("delta-galil", "Delta Galil", "iem", "deltagalil.com", url="https://www.deltagalil.com/careers/"),
    _source("tnuva", "Tnuva", "iem", "tnuva.co.il", url="https://www.tnuva.co.il/jobs/"),
    _source("unilever-israel", "Unilever Israel", "iem", "unilever.com", url="https://careers.unilever.com/en/israel"),
    _source("pg-israel", "Procter & Gamble Israel", "iem", "pg.com", url="https://www.pgcareers.com/location-israel", enabled=True),
    _source("loreal-israel", "L'Oréal Israel", "iem", "loreal.com", url="https://careers.loreal.com/"),
    _source("jnj-israel", "Johnson & Johnson Israel", "ee", "jnj.com", url="https://www.careers.jnj.com/", enabled=True),
    _source("rambam", "Rambam", "ee", "rambam.org.il", url="https://www.rambam.org.il/about-rambam/careers/"),
    _source("hadassah", "Hadassah", "ee", "hadassah.org.il", url="https://he.hadassah.org.il/wanted/careers/"),
    _source("meuhedet", "Meuhedet", "cs", "meuhedet.co.il", url="https://www.meuhedet.co.il/en/career-at-meuhedet/"),
    _source("assuta", "Assuta Medical Centers", "ee", "assuta.co.il", url="https://www.assuta.co.il/about/jobs/"),
    _source("bezeq", "Bezeq", "ee", "bezeq.co.il", url="https://www.bezeq.co.il/career/"),
    _source("cellcom", "Cellcom", "ee", "cellcom.co.il", url="https://www.cellcom.co.il/career/"),
    _source("partner", "Partner", "ee", "partner.co.il", url="https://www.partner.co.il/n/career"),
    _source("hot", "HOT", "ee", "hot.net.il", url="https://www.hot.net.il/heb/career/"),
    _source("electra-group", "Electra Group", "ee", "electra.co.il", url="https://www.electra.co.il/career/משרות"),
    _source("mekorot", "Mekorot", "ee", "mekorot.co.il", url="https://www.mekorot.co.il/careers/"),
    _source("iec", "Israel Electric Corporation", "ee", "iec.co.il", url="https://www.iec.co.il/careers"),
)


assert len(EXPANDED_EMPLOYER_SOURCES) == 100
assert len({item["company_name"].casefold() for item in EXPANDED_EMPLOYER_SOURCES}) == 100
